### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by s6pepaul**
PR #111  introduced gen_amp_V2 which needs two command line options. These should be provided to MCwrapper through the first line in the gen_amp_V2 config file. This makes sure that gluex_MC.py contains as little generator specific code as possible. This is needed to ensure easy submission to the OSG. Therefore this PR undos some of the changes by taking out the lower vertex and upper vertex options.

### CODE REVIEW

**Comment by mashephe** [comment]
It seems like this code will disable use of gen_amp_V2 in MCWrapper?  If this is true, is there a way we can make a change that is both compliant with expectations and allows gen_amp_v2 to run?

**Comment by T-Britton** [comment]
it shouldn't.  MCwrapper pulled a trick a long time ago by coopting the first line (which is commented out). here is the top of the gen_amp config file for MCwrapper:
#
#The above line is used to provide additional options to the generator within the wrapper.  These options do NOT include output file names, run numbers, and number of events which are controlled by the wrapper
#####################################
####	THIS IS A CONFIG FILE	 ####
#####################################
....

MCwrapper takes the first line and appends any options to the generator call.  This enables MCwrapper to more generically handle a host of generator specific possibilities that would just over-clutter the MC.config file.  

This is how gen_amp was integrated, unsure of why MC.config or MCwrapper command line options were use in the initial v2 implementation.  We just need to ensure that the appending mechanism is used for gen_amp_v2 as it is for gen_amp

**Comment by mashephe** [comment]
OK, that sounds reasonable.  Maybe @KSaldan can weigh in as he made these changes.  I'm not sure if he is getting these messages.

**Comment by KSaldan** [comment]
To chime in, Peter made a change to the MCWrapper version on the container to remove these variables and include them in the first line of the generator config file as you have mentioned. I managed to generate MC using this option with no trouble, you can make the changes.

**Review by mashephe — APPROVED** [review]
Seems good and has been tested to work.

**Pull request merged**
